### ISSUE TITLE
Bug: Unwanted space in the hero section.

### ISSUE THREAD

**Issue by shamimbinnur** [open-sauced/hot#338] opened 2022-09-13 15:21 UTC
### Describe the bug

On the left corner of the hero section, there are some spaces that were not supposed to be there.

![Screenshot 2022-09-13 at 9 08 17 PM](https://user-images.githubusercontent.com/48399373/189941035-8e1a999a-1324-4f8e-8181-350e0be4f2d3.png)
![Screenshot 2022-09-13 at 9 08 43 PM](https://user-images.githubusercontent.com/48399373/189941131-30ea9070-6cbb-403a-b3c9-a6bfcac7b239.png)

### Steps to reproduce

Go to the home page of the site from from large screen device, look at the left corner of the hero section you will see some spaces.

### Affected services

hot.opensauced.pizza

### Platforms

Desktop, Tablet

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment] 2022-09-13 17:53
duplicate of #227 🍕

**Comment by shamimbinnur** [comment] 2022-09-13 18:03
> duplicate of #227 🍕

Oh, I see! So for that :((

**Comment by 0-vortex** [comment] 2022-09-13 20:32
> > duplicate of #227 🍕
> 
> Oh, I see! So for that :((

No worries, closing this for now, feel free to pick it up if you like! :D

**Closed by 0-vortex** 2022-09-13 20:32 UTC
Labels: 🐛 bug
