### ISSUE TITLE
Feature: react loading skeleton

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/hot#276] opened 2022-08-01 18:59 UTC
### Type of feature

🍕 Feature

### Current behavior

Affect all the repo. The sooner, the better. 

### Suggested solution

In open-sauced we have `react-loading-skeleton` for the user It would be nice to implement this feature in hot to avoid 'break the app' [open-sauced](https://github.com/open-sauced/open-sauced/blob/main/package.json#L56)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment] 2022-08-01 20:26
I would prefer we first implement something like [useAsync](https://usehooks.com/useAsync/) and then focus on this issue, which is improving the visual feedback of the async functions. Most of the hot open sauced content relies on data fetching:
- hot repositories
- my votes
- list repositories

Having a standardized UI vs data loading async distinction we can then apply nice skeletons using the proposed library, having this distinction also helps reduce implementation difficulty for this issue, as it would then require installing and adding to the components doing async fetches only! 🍕

**Comment by NsdHSO** [comment] 2022-08-02 06:20
I don't think in this way, because this feature should be implemented with/without `useAsync`.  But please create a new ticket with this hook.

**Comment by 0-vortex** [comment] 2022-08-02 12:01
> I don't think in this way, because this feature should be implemented with/without `useAsync`.  But please create a new ticket with this hook. 

You opened the ticket up as a feature, in the sense of feature design, it's something worth discussing. If it is not a feature and just a style: improvement there's not much to talk about and you could just as well screenshot what you are experimenting with as a proposal. 

Was also hoping triaging issues could be done as a group effort rather than breaking it apart into multiple issues we are not willing to discuss 😅

**Comment by bdougie** [comment] 2022-08-02 13:13
FWIW, Suspense and useAsync are related to loading skeletons. 

> I don't think in this way, because this feature should be implemented with/without useAsync. But please create a new ticket with this hook.

As mentioned in this issue, https://github.com/open-sauced/hot/issues/270, this is already a solved problem in [app.opensauced.pizza](https://github.com/open-sauced/open-sauced). 

This is a duplicate of my issue, but not a big deal if this is the place to discuss the implementation. Is this something you are looking to test out @NsdHSO?

**Comment by bdougie** [comment] 2022-08-02 13:15
> This is a duplicate of my issue, but not a big deal if this is the place to discuss the implementation. Is this something you are looking to test out @NsdHSO?

NVM I see your PR

**Comment by NsdHSO** [comment] 2022-08-03 19:31
For skeleton, I created one demo, to [did](https://gitpodio-createreactapp-ib13co9ba65.ws-eu54.gitpod.io/) this issue `good first issues `

**Comment by 0-vortex** [comment] 2022-08-07 00:43
`.take`

**Closed** 2022-08-09 23:00 UTC
Labels: 💡 feature
