### ISSUE TITLE
Bug: hot repositories section avatars are too big

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/hot#261] opened 2022-07-29 14:18 UTC
### Describe the bug

Make the [Avatar component](https://github.com/open-sauced/hot/blob/main/src/components/Avatar.tsx) resizable so it can take the initial 5px size described in the design:

<img width="427" alt="Screenshot 2022-07-29 at 16 14 26" src="https://user-images.githubusercontent.com/237133/181779704-06beb3b6-a6fd-4ca4-b8ea-4ee87a1702c0.png">

### Steps to reproduce

1. Go to https://hot.opensauced.pizza
2. The avatars should look like this:

<img width="433" alt="Screenshot 2022-07-29 at 16 16 07" src="https://user-images.githubusercontent.com/237133/181779762-8e835abc-9a8e-4e7d-8c8c-c96b72134fb7.png">

### Affected services

hot.opensauced.pizza

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment] 2022-07-29 15:01
Is this a duplicate of #204? The PR that implemented this did not fully implement this feature.

Also #242 has a better implementation. Whatever is done should be reused.

**Comment by 0-vortex** [comment] 2022-07-29 15:04
> Is this a duplicate of #204? The PR that implemented this did not fully implement this feature.
> 
> Also #242 has a better implementation. Whatever is done should be reused.

There were some markup changes required when switching from static hot repos to database ones, I replaced the avatar imgs with the Actual avatar component, which is hard-sized right now.

If that PR updates the avatar component then it should merge with main to get the updated visual changes from upstream 🍕

**Closed** 2022-07-30 13:29 UTC
Labels: 🐛 bug, 🛑 blocked
