### ISSUE TITLE
Bug: no key is included in each menu in SecondaryNav

### ISSUE THREAD

**Issue by ddsuhaimi** [open-sauced/hot#229] opened 2022-07-25 03:24 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/30659198/180692919-b5d11a25-8a05-4bd9-8bc2-305e4865cd5b.png)

Per react [docs](https://reactjs.org/docs/lists-and-keys.html), a key should be added if we render a list.

### Steps to reproduce

1. Clone the repository
2. Start the app locally
3. Check out developer console

### Affected services

hot.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment] 2022-07-25 03:48
Thanks for adding this in, however it's a duplicate of #222 - will close this as it has been released on beta branch!

**Closed by 0-vortex** 2022-07-25 03:48 UTC
Labels: good first issue, 🐛 bug, released on @beta
