### ISSUE TITLE
Bug: Relative dates are not available in search results

### ISSUE THREAD

**Issue by htuerker** [open-sauced/hot#188] opened 2022-06-19 17:37 UTC
### Describe the bug

Relative date implementation by #185 isn't available for the `Avatar` on search results. 
![Screen Shot 2022-06-19 at 20 21 02](https://user-images.githubusercontent.com/46192266/174492938-24867807-3a5e-43a7-b342-4cbfc1dea873.png)

Suggested solution:

1. I recommend moving the `dayjs(timestamp).fromNow()` conversion into `Avatar` component. 

https://github.com/open-sauced/hot/blob/2025ecc83c22a07432b3ff807d10ce787855827e/src/components/PostGrid.tsx#L41-L48

https://github.com/open-sauced/hot/blob/2025ecc83c22a07432b3ff807d10ce787855827e/src/components/Avatar.tsx#L57-L59

### Steps to reproduce

1-) Visit [https://beta.hot.opensauced.pizza/](https://beta.hot.opensauced.pizza/)
2-) Search any repository that has recent contributors
3-) Hover contributor's Avatar.

### Affected services

hot.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment] 2022-06-19 17:39
potentially duplicate of #186 tho it can be beta'd using the same reasoning as #185

**Comment by blackgirlbytes** [comment] 2022-06-19 19:10
.take

**Closed** 2022-08-04 01:40 UTC
Labels: 🐛 bug, released, released on @beta
